name: Feature
description: Propose a new feature or enhancement
title: "[Feature]: "
labels: ["feature"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature.
      placeholder: What should the system do?
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Define measurable criteria.
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Additional context or constraints.
